### PR TITLE
Fix: GetCustomVariable - Invalid result for Visit and Event scoped custom variableGetCustomVariables 

### LINKED ISSUE #37: GetCustomVariable - Invalid result for Visit and Event scoped custom variables
Discovered by @ptr1120 in https://github.com/piwik/piwik-dotnet-tracker/pull/36

Querying for an Event scoped custom variable results in an exception.

Querying for a Visit scoped custom variable attempts to return an equivalently named Event scoped custom variable.

The only valid case is querying for a Page scoped custom variable.

The bug was introduced here https://github.com/piwik/piwik-dotnet-tracker/commit/caba0423fea7b63300476b4da2eb06a7cef53c1c#diff-3ef10527762c9550c23f3f369808ffa6R290

The test should not be negated as in https://github.com/piwik/piwik-php-tracker/blob/master/PiwikTracker.php#L294

### PR DESCRIPTION
**Pull request by ptr1120**
In order to fix #37:

* added test project with NUnit
* added test for GetCustomVariable()
* implemented fix for #37
* fixed issue introduced in commit 4141d695a8f3e6625ab06478bfef59b21c5e52de (wrong variable test in constructor)

### CODE REVIEW

**Comment by julienmoumne** [comment]
Hi Peter, thanks for submitting the first automated test.

I am having difficulties building the project, can you have a look at this screen shot : 

image

Don't you have the same error on your IDE? If not, is there something I need to configure on my machine?

Also, I forgot to catch this before, wouldn't it be nicer to move `PiwikTracker.DebugLastRequestedUrl` to `TrackingResponse.url` ?

Except for these two comments it looks good!

**Comment by ptr1120** [comment]
Hi Julien,

sorry for the issue with `DebugLastRequestUrl`, I did not see the compilation error after making this property as instance variable in commit 99860e7638fe749f4dd39c155505fdcec6fae8c1.
I also think it would be useful to have the `DebugLastRequestUrl ` as property `RequestUrl ` in the `TrackingResponse`. 
Should I add a fix to this PR or is it better to add a new PR?

**Comment by julienmoumne** [comment]
No worries, we'll soon have travis checking-out these bugs!

Same PR is fine, thanks.

**Comment by ptr1120** [comment]
Appending of commits isn't possible because my fork differs. Please merge this PR first.
